import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Image from 'next/image'
import React from 'react'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

let ST = 1499.99

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='mx-10'>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
