import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Image from 'next/image'
import React from 'react'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MRUBIKS',
  description: 'Generated by Muhammad Mehdi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={`${inter.className}`}>
        <div className='w-[97%] max-w-[2300px] mx-auto'>
      <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
